### ISSUE TITLE
Guile REPL is started when in Racket REPL

### ISSUE THREAD

**Issue by Ramapitecus** [jaor/geiser#132]
This only happens When `geiser-mode-start-repl-p` is `t`, and in the racket repl. (I tested guile repl, don't have chicken installed at the moment)

To reproduce:
```
    $ emacs -Q
    M-x load-file /path/to/geiser.el
    M-: (setq geiser-mode-start-repl-p t)
    M-x run-racket
    racket@> (*
```

Anything you type after the open paren will trigger this. 

Here Is *geiser message* After `C-u M-x geiser-show-logs`:

```
INFO: REQUEST: <2>: ,geiser-eval #f #f ,apply geiser:autodoc ('(*))

INFO: REQUEST: <1>: ,use (geiser emacs)
'done

INFO: RETORT: ((error (key . retort-syntax)) (output . "$1 = done
scheme@(guile-user)> "))

INFO: <1>: processed

INFO: REQUEST: <2>: ,geiser-eval (geiser evaluation) ge:set-warnings ((quote medium)) ()

INFO: RETORT: ((result "#<unspecified>") (output . ""))

INFO: <2>: processed

INFO: <2>: processed
```

Im using 
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6) of 2015-09-09 on foutrelis
On a 64 bits Arch linux 
And geiser 20160215.1732 from melpa. 

I'ts late so I didn't track this further. I will update If I learn anything new.

**Comment by jaor** [comment]
this is a funny one! i can reproduce it, and i will take a look as soon
as i can... thanks for the report!

**Comment by fice-t** [comment]
I got a backtrace for this:

```elisp
  run-geiser(guile)
  geiser-mode(1)
  turn-on-geiser-mode()
  geiser-mode--maybe-activate()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook scheme-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook scheme-mode-hook))
  run-mode-hooks(scheme-mode-hook)
  scheme-mode()
  geiser-syntax--font-lock-buffer()
  geiser-autodoc--str(("let" 0) (("name" . let) ("args" (("required" \.\.\.) ("optional") ("key"))) ("module" . "racket/private/qq-and-or")))
  geiser-autodoc--autodoc((("let" 0)) (("let" ("name" . let) ("args" (("required" \.\.\.) ("optional") ("key"))) ("module" . "racket/private/qq-and-or"))))
  geiser-autodoc--show-signatures(((result "((let (\"name\" . let) (\"args\" ((\"required\" ...) (\"optional\") (\"key\"))) (\"module\" . \"racket/private/qq-and-or\")))") (output . "")))
  geiser-con--process-completed-request(((:id . 2) (:string . ",geiser-eval #f #f ,apply geiser:autodoc ('(let))") (:continuation . geiser-autodoc--show-signatures) (:buffer . #<buffer * Racket REPL *>) (:connection t (:filter . comint-output-filter) (:tq ((nil "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)" #0 . geiser-con--process-completed-request)) #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>) (:tq-filter lambda (p s) (geiser-con--tq-filter (quote (((nil "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)" #0 . geiser-con--process-completed-request)) #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>)) s)) (:eot . "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)") (:prompt . "\\(mzscheme\\|racket\\)@[^ ]*> ") (:debug-prompt) (:is-debugging) (:count . 2) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data (1 ((:id . 1) (:string . ",geiser-eval geiser/user #f (image-cache)") (:continuation) (:buffer . #<buffer * Racket REPL *>) (:connection t (:filter . comint-output-filter) (:tq (...) #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>) (:tq-filter lambda (p s) (geiser-con--tq-filter ... s)) (:eot . "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)") (:prompt . "\\(mzscheme\\|racket\\)@[^ ]*> ") (:debug-prompt) (:is-debugging) (:count . 2) #2)) ...))))) "((result \"((let (\\\"name\\\" . let) (\\\"args\\\" ((\\\"required\\\" ...) (\\\"optional\\\") (\\\"key\\\"))) (\\\"module\\\" . \\\"racket/private/qq-and-or\\\")))\") (output . \"\"))\nracket@> ")
  geiser-con--tq-filter((((nil "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)" ((:id . 2) (:string . ",geiser-eval #f #f ,apply geiser:autodoc ('(let))") (:continuation . geiser-autodoc--show-signatures) (:buffer . #<buffer * Racket REPL *>) (:connection t (:filter . comint-output-filter) (:tq #1 #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>) (:tq-filter lambda (p s) (geiser-con--tq-filter (quote #0) s)) (:eot . "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)") (:prompt . "\\(mzscheme\\|racket\\)@[^ ]*> ") (:debug-prompt) (:is-debugging) (:count . 2) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data (1 (... ... ... ... ...) ...))))) . geiser-con--process-completed-request)) #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>) "racket@> ")
  (lambda (p s) (geiser-con--tq-filter (quote (((nil "\\(\n\\(mzscheme\\|racket\\)@[^ ]*> \\)" ((:id . 2) (:string . ",geiser-eval #f #f ,apply geiser:autodoc ('(let))") (:continuation . geiser-autodoc--show-signatures) (:buffer . #<buffer * Racket REPL *>) (:connection t ... ... ... ... ... ... ... ... ...)) . geiser-con--process-completed-request)) #<process Racket REPL> . #<buffer  tq-temp-Racket REPL>)) s))(#<process Racket REPL> "racket@> ")
```

Looks like `geiser-syntax--font-lock-buffer` activates Geiser when it shouldn't.

**Comment by jaor** [comment]
94210cd should fix this one, although there's still an unrelated little
glitch (fontified scheme strings not always use extra font lock keywords).

**Comment by fice-t** [comment]
@jaor It looks like there's a typo in that commit (94210cd), since I get this compile warning:

```
In geiser-syntax--font-lock-buffer:
geiser-syntax.el:487:12:Warning: reference to free variable `buffer'
```

**Comment by fice-t** [comment]
Otherwise it seems to be fixed.

**Comment by jaor** [comment]
yes... one of the commits after that one fixes the typo, i think.

**Comment by fice-t** [comment]
I think that's a different typo. This one involves an extra parenthesis after `scheme-mode` leaving `buffer` to be a free variable. It's still present in the last commit.

**Comment by jaor** [comment]
sorry for being this careless.  should be fixed in a2da78d.  thanks for
your patience.

**Comment by fice-t** [comment]
No worries, I've done the same thing myself.

The issue seems to be good now.

**Comment by jaor** [comment]
thanks for checking. @Ramapitecus, i'm closing the issue: please re-open it if the fix doesn't work for you, thanks!
